# Generated by Django 5.1.7 on 2026-05-17 03:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0006_alter_licenserenewal_expiration_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="licenserenewal",
            name="expiration_date",
            field=models.DateField(default=datetime.date(2026, 6, 17)),
        ),
    ]
