# Generated by Django 5.1.7 on 2026-05-17 03:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0007_alter_licenserenewal_expiration_date"),
        ("users", "0003_user_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="users",
                to="users.userrole",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="users",
                to="client.tenant",
            ),
        ),
        migrations.AlterField(
            model_name="usergroup",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="user_groups",
                to="client.tenant",
            ),
        ),
        migrations.AlterField(
            model_name="userrole",
            name="name",
            field=models.CharField(
                choices=[
                    ("SUPER_ADMIN", "Super Admin"),
                    ("STAFF", "Staff"),
                    ("CUSTOMER", "Customer"),
                ],
                default="CUSTOMER",
                max_length=50,
                unique=True,
            ),
        ),
    ]
